version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: a
      MONGO_INITDB_ROOT_PASSWORD: 1

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: a #DEFAULT admin - pass
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1
      ME_CONFIG_MONGODB_URL: mongodb://a:1@mongo:27017/
